# Generated by Django 3.1.3 on 2020-11-29 04:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('name', models.CharField(max_length=55)),
                ('desc', models.TextField(max_length=280)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Only positive integers allowed')])),
                ('primkey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=105, unique=True)),
                ('primkey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('name', models.CharField(max_length=55)),
                ('desc', models.TextField(max_length=280)),
                ('primkey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('users', models.ManyToManyField(help_text='Usuarios pertenecientes al grupo.', to='applostickes.User')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('name', models.CharField(max_length=55)),
                ('desc', models.TextField(max_length=280)),
                ('primkey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mapping', models.CharField(help_text='Para definir que paga cada usuario seguir el siguiente formato: 1,2;2,3,4. ; por cada producto. , por cada usuario responsable.', max_length=55)),
                ('elements', models.ManyToManyField(help_text='Introduce elementos de la transaccion.', to='applostickes.Element')),
                ('payers', models.ManyToManyField(help_text='Usuarios entre los que pagar la transaccion.', to='applostickes.User')),
                ('user_group', models.ForeignKey(help_text='Grupo al cual pertenence la transaccion.', on_delete=django.db.models.deletion.CASCADE, to='applostickes.usergroup')),
            ],
        ),
    ]
