# Generated by Django 3.1.3 on 2020-12-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applostickes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mapping',
            field=models.CharField(help_text='Para definir que paga cada usuario seguir el siguiente formato: 1,2;2,3,4. ; por cada producto. , por cada usuario responsable.', max_length=280),
        ),
    ]
