# Generated by Django 3.1.3 on 2020-12-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applostickes', '0011_auto_20201216_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
