# Generated by Django 3.1.3 on 2020-12-25 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applostickes', '0014_auto_20201225_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='django_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
