# Generated by Django 3.1.3 on 2020-12-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applostickes', '0016_auto_20201225_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'get_latest_by': 'creation_date'},
        ),
        migrations.AddField(
            model_name='element',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
