# Generated by Django 3.1.3 on 2020-12-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applostickes', '0017_auto_20201226_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='desc',
        ),
    ]
