# Generated by Django 3.1.3 on 2020-12-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applostickes', '0018_remove_element_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'get_latest_by': 'creation_date', 'ordering': ['creation_date']},
        ),
    ]
