# Generated by Django 3.1.3 on 2020-12-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applostickes', '0019_auto_20201226_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'get_latest_by': 'creation_date', 'ordering': ['-creation_date']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
